package com.lexia.backend.service.ai;

import com.lexia.backend.dto.ai.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;
import java.util.UUID;

/**
 * Service interface for AI-powered flashcard operations.
 * Provides methods for generating, managing, and studying flashcard decks.
 * 
 * <p>
 * Features:
 * </p>
 * <ul>
 * <li>AI-generated flashcards from lesson content via Google Gemini</li>
 * <li>Manual deck creation and management</li>
 * <li>SM-2 spaced repetition algorithm for optimal learning</li>
 * <li>Progress tracking and mastery levels</li>
 * <li>Study session management</li>
 * </ul>
 * 
 * <p>
 * Deck Sources:
 * </p>
 * <ul>
 * <li>LESSON - Auto-generated from completed lesson vocabulary</li>
 * <li>AI_GENERATED - Generated by AI based on user preferences</li>
 * <li>USER_CREATED - Manually created by the user</li>
 * </ul>
 * 
 * @author LEXIA Team
 * @since Sprint 5
 * @see com.lexia.backend.entity.FlashcardDeck
 * @see com.lexia.backend.entity.UserFlashcardProgress
 */
public interface FlashcardService {

    // ========== Generation Methods ==========

    /**
     * Generates a flashcard deck from lesson content using AI.
     * 
     * <p>
     * This method extracts vocabulary and key terms from the lesson content,
     * then uses Google Gemini AI to generate comprehensive flashcards with
     * definitions, example sentences, and pronunciation.
     * </p>
     * 
     * <p>
     * If AI generation fails, a fallback strategy is used to create
     * basic flashcards from extracted vocabulary.
     * </p>
     * 
     * @param request the generation request containing lessonId and options
     * @param userId  the ID of the user requesting the generation
     * @return the generated flashcard deck DTO
     * @throws com.lexia.backend.exception.ResourceNotFoundException if lesson is
     *                                                               not found
     * @throws com.lexia.backend.exception.ai.AiRateLimitException   if user has
     *                                                               exceeded their
     *                                                               quota
     * @throws IllegalStateException                                 if user already
     *                                                               has a deck for
     *                                                               this lesson
     */
    FlashcardDeckDTO generateFromLesson(GenerateFlashcardsDTO request, UUID userId);

    /**
     * Generates a flashcard deck from a topic using AI.
     * 
     * <p>
     * This method uses Google Gemini AI to generate vocabulary flashcards
     * based on the given topic and CEFR level, with definitions, example
     * sentences, and pronunciation.
     * </p>
     * 
     * @param request the generation request containing topic and options
     * @param userId  the ID of the user requesting the generation
     * @return the generated flashcard deck DTO
     * @throws com.lexia.backend.exception.ai.AiRateLimitException if user has
     *                                                             exceeded their
     *                                                             quota
     * @throws com.lexia.backend.exception.ai.AiServiceException   if AI generation
     *                                                             fails
     */
    FlashcardDeckDTO generateFromTopic(GenerateFlashcardsByTopicDTO request, UUID userId);

    // ========== Deck CRUD Methods ==========

    /**
     * Creates a new flashcard deck manually.
     * 
     * @param request the deck creation request
     * @param userId  the owner user ID
     * @return the created deck DTO
     * @throws IllegalArgumentException if request validation fails
     */
    FlashcardDeckDTO createDeck(CreateFlashcardDeckDTO request, UUID userId);

    /**
     * Retrieves a deck by ID.
     * 
     * @param deckId the deck UUID
     * @param userId the user ID (for ownership verification)
     * @return the deck DTO with cards
     * @throws com.lexia.backend.exception.ResourceNotFoundException     if deck not
     *                                                                   found
     * @throws org.springframework.security.access.AccessDeniedException if user
     *                                                                   doesn't own
     *                                                                   the deck
     */
    FlashcardDeckDTO getDeck(UUID deckId, UUID userId);

    /**
     * Retrieves a deck by ID without cards (lightweight).
     * 
     * @param deckId the deck UUID
     * @param userId the user ID (for ownership verification)
     * @return the deck DTO without cards
     * @throws com.lexia.backend.exception.ResourceNotFoundException if deck not
     *                                                               found
     */
    FlashcardDeckDTO getDeckSummary(UUID deckId, UUID userId);

    /**
     * Lists all decks for a user with pagination.
     * 
     * @param userId   the user ID
     * @param pageable pagination parameters
     * @return page of deck DTOs (without cards for performance)
     */
    Page<FlashcardDeckDTO> getUserDecks(UUID userId, Pageable pageable);

    /**
     * Lists all decks for a user without pagination.
     * 
     * @param userId the user ID
     * @return list of deck DTOs (without cards)
     */
    List<FlashcardDeckDTO> getUserDecks(UUID userId);

    /**
     * Lists decks by source type.
     * 
     * @param userId     the user ID
     * @param sourceType the source type (LESSON, AI_GENERATED, USER_CREATED)
     * @return list of matching deck DTOs
     */
    List<FlashcardDeckDTO> getUserDecksBySourceType(UUID userId, String sourceType);

    /**
     * Updates an existing deck.
     * 
     * @param deckId  the deck UUID
     * @param request the update request
     * @param userId  the user ID (for ownership verification)
     * @return the updated deck DTO
     * @throws com.lexia.backend.exception.ResourceNotFoundException     if deck not
     *                                                                   found
     * @throws org.springframework.security.access.AccessDeniedException if user
     *                                                                   doesn't own
     *                                                                   the deck
     */
    FlashcardDeckDTO updateDeck(UUID deckId, UpdateFlashcardDeckDTO request, UUID userId);

    /**
     * Deletes a deck and all associated progress records.
     * 
     * @param deckId the deck UUID
     * @param userId the user ID (for ownership verification)
     * @throws com.lexia.backend.exception.ResourceNotFoundException     if deck not
     *                                                                   found
     * @throws org.springframework.security.access.AccessDeniedException if user
     *                                                                   doesn't own
     *                                                                   the deck
     */
    void deleteDeck(UUID deckId, UUID userId);

    // ========== Card Management Methods ==========

    /**
     * Adds a card to an existing deck.
     * 
     * @param deckId  the deck UUID
     * @param cardDTO the card to add
     * @param userId  the user ID (for ownership verification)
     * @return the updated deck DTO
     * @throws com.lexia.backend.exception.ResourceNotFoundException if deck not
     *                                                               found
     */
    FlashcardDeckDTO addCard(UUID deckId, FlashcardCardDTO cardDTO, UUID userId);

    /**
     * Updates a card in an existing deck.
     * 
     * @param deckId    the deck UUID
     * @param cardIndex the index of the card to update (0-based)
     * @param cardDTO   the updated card data
     * @param userId    the user ID (for ownership verification)
     * @return the updated deck DTO
     * @throws com.lexia.backend.exception.ResourceNotFoundException if deck or card
     *                                                               not found
     */
    FlashcardDeckDTO updateCard(UUID deckId, int cardIndex, FlashcardCardDTO cardDTO, UUID userId);

    /**
     * Removes a card from a deck.
     * 
     * @param deckId    the deck UUID
     * @param cardIndex the index of the card to remove (0-based)
     * @param userId    the user ID (for ownership verification)
     * @return the updated deck DTO
     * @throws com.lexia.backend.exception.ResourceNotFoundException if deck or card
     *                                                               not found
     */
    FlashcardDeckDTO removeCard(UUID deckId, int cardIndex, UUID userId);

    // ========== Study Session Methods ==========

    /**
     * Gets a study session with cards due for review.
     * 
     * <p>
     * Returns cards ordered by priority:
     * </p>
     * <ol>
     * <li>Overdue cards (most overdue first)</li>
     * <li>New cards (never reviewed)</li>
     * <li>Regular due cards</li>
     * </ol>
     * 
     * @param deckId   the deck UUID
     * @param userId   the user ID
     * @param maxCards maximum number of cards to include (default: 20)
     * @return the study session DTO with cards and progress
     * @throws com.lexia.backend.exception.ResourceNotFoundException if deck not
     *                                                               found
     */
    FlashcardStudySessionDTO getStudySession(UUID deckId, UUID userId, Integer maxCards);

    /**
     * Submits review results for studied cards.
     * 
     * <p>
     * Updates the SM-2 spaced repetition data for each reviewed card,
     * including ease factor, interval, next review date, and mastery level.
     * </p>
     * 
     * @param deckId  the deck UUID
     * @param userId  the user ID
     * @param results the review results containing quality ratings per card
     * @return updated study session with next due cards
     * @throws com.lexia.backend.exception.ResourceNotFoundException if deck not
     *                                                               found
     */
    FlashcardStudySessionDTO submitReview(UUID deckId, UUID userId, FlashcardReviewResultDTO results);

    /**
     * Gets a practice session with all cards regardless of due status.
     * 
     * <p>
     * Practice mode allows reviewing cards without affecting spaced repetition
     * data.
     * Cards are returned in random order.
     * </p>
     * 
     * @param deckId   the deck UUID
     * @param userId   the user ID
     * @param maxCards maximum number of cards to include
     * @return the practice session DTO with all available cards
     * @throws com.lexia.backend.exception.ResourceNotFoundException if deck not
     *                                                               found
     */
    FlashcardStudySessionDTO getPracticeSession(UUID deckId, UUID userId, Integer maxCards);

    // ========== Progress & Statistics Methods ==========

    /**
     * Gets detailed progress for a deck.
     * 
     * @param deckId the deck UUID
     * @param userId the user ID
     * @return list of progress records for all cards in the deck
     */
    List<FlashcardProgressDTO> getDeckProgress(UUID deckId, UUID userId);

    /**
     * Gets the count of cards due for review in a deck.
     * 
     * @param deckId the deck UUID
     * @param userId the user ID
     * @return number of cards due for review
     */
    long getDueCardCount(UUID deckId, UUID userId);

    /**
     * Gets the count of cards due for review across all user's decks.
     * 
     * @param userId the user ID
     * @return total number of cards due for review
     */
    long getTotalDueCardCount(UUID userId);

    /**
     * Checks if a user already has a deck generated from a specific lesson.
     * 
     * @param lessonId the lesson ID
     * @param userId   the user ID
     * @return true if deck exists for the lesson
     */
    boolean hasLessonDeck(Long lessonId, UUID userId);

    /**
     * Gets the deck generated from a specific lesson (if exists).
     * 
     * @param lessonId the lesson ID
     * @param userId   the user ID
     * @return the deck DTO or null if not found
     */
    FlashcardDeckDTO getLessonDeck(Long lessonId, UUID userId);

    /**
     * Gets deck statistics summary for a user.
     * 
     * @param userId the user ID
     * @return statistics DTO with deck counts and card totals
     */
    FlashcardStudySessionDTO.DeckStatsDTO getUserDeckStats(UUID userId);
}
