package com.lexia.backend.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Entity representing a flashcard deck for vocabulary learning.
 * 
 * <p>Flashcard decks can be created from three sources:</p>
 * <ul>
 *   <li><b>LESSON</b> - Auto-generated from completed lesson vocabulary</li>
 *   <li><b>AI_GENERATED</b> - Generated by AI based on user's CEFR level/topic</li>
 *   <li><b>USER_CREATED</b> - Manually created by the user</li>
 * </ul>
 * 
 * <p>Cards are stored as JSONB array with the following structure:</p>
 * <pre>
 * [{
 *   "front": "vocabulary word",
 *   "back": {
 *     "definition": "...",
 *     "partOfSpeech": "noun",
 *     "pronunciation": "/prəˌnʌnsiˈeɪʃn/",
 *     "exampleSentence": "...",
 *     "synonyms": ["..."],
 *     "collocations": ["..."]
 *   },
 *   "tags": ["business", "b2"],
 *   "difficulty": 2
 * }]
 * </pre>
 * 
 * @author LEXIA Team
 * @since Sprint 5
 * @see UserFlashcardProgress
 */
@Entity
@Table(name = "flashcard_decks", indexes = {
    @Index(name = "idx_flashcard_decks_user", columnList = "user_id"),
    @Index(name = "idx_flashcard_decks_source", columnList = "source_type, source_id"),
    @Index(name = "idx_flashcard_decks_level", columnList = "cefr_level"),
    @Index(name = "idx_flashcard_decks_user_source", columnList = "user_id, source_type"),
    @Index(name = "idx_flashcard_decks_user_created", columnList = "user_id, created_at")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(of = "id")
@ToString(exclude = {"cards", "progressRecords"})
public class FlashcardDeck {

    /**
     * Source type enum matching database CHECK constraint.
     */
    public enum SourceType {
        /** Auto-generated from a completed lesson */
        LESSON("lesson"),
        /** Generated by AI based on user preferences */
        AI_GENERATED("ai_generated"),
        /** Manually created by the user */
        USER_CREATED("user_created");

        private final String value;

        SourceType(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        /**
         * Converts database value to enum.
         * @param value database string value
         * @return corresponding SourceType enum
         * @throws IllegalArgumentException if value doesn't match any enum
         */
        public static SourceType fromValue(String value) {
            for (SourceType type : values()) {
                if (type.value.equals(value)) {
                    return type;
                }
            }
            throw new IllegalArgumentException("Unknown source type: " + value);
        }
    }

    /**
     * Primary key - UUID generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Reference to the user who owns this deck.
     * Required field - each deck belongs to exactly one user.
     */
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    /**
     * Deck title displayed to the user.
     */
    @NotBlank(message = "Deck title is required")
    @Size(max = 200, message = "Deck title must not exceed 200 characters")
    @Column(nullable = false, length = 200)
    private String title;

    /**
     * Optional deck description.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Source type indicating how the deck was created.
     * Stored as lowercase string in database.
     */
    @Convert(converter = SourceTypeConverter.class)
    @Column(name = "source_type", length = 20)
    private SourceType sourceType;

    /**
     * Reference to source lesson ID when sourceType is LESSON.
     * Must be set when sourceType is LESSON, null otherwise.
     */
    @Column(name = "source_id")
    private Long sourceId;

    /**
     * CEFR level of the vocabulary in this deck.
     * Validated against A1, A2, B1, B2, C1, C2.
     */
    @Column(name = "cefr_level", length = 2)
    private String cefrLevel;

    @Converter
    public static class SourceTypeConverter implements AttributeConverter<SourceType, String> {
        @Override
        public String convertToDatabaseColumn(SourceType attribute) {
            return attribute == null ? null : attribute.getValue();
        }

        @Override
        public SourceType convertToEntityAttribute(String dbData) {
            return dbData == null ? null : SourceType.fromValue(dbData);
        }
    }

    /**
     * Flashcard data stored as JSONB array.
     * Each card contains front (word), back (details), tags, and difficulty.
     * 
     * @see FlashcardCard for the Java representation
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "cards", columnDefinition = "jsonb", nullable = false)
    @Builder.Default
    private List<FlashcardCard> cards = new ArrayList<>();

    /**
     * Denormalized count of cards in the deck.
     * Updated automatically when cards are modified.
     */
    @Column(name = "card_count")
    @Builder.Default
    private Integer cardCount = 0;

    /**
     * Timestamp when the deck was created.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp when the deck was last updated.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Progress records for this deck (one per user per card).
     * Lazily loaded to avoid N+1 queries.
     */
    @OneToMany(mappedBy = "deck", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<UserFlashcardProgress> progressRecords = new ArrayList<>();

    // ========== Helper Methods ==========

    /**
     * Updates the card count based on the current cards list size.
     * Should be called after adding/removing cards.
     */
    public void updateCardCount() {
        this.cardCount = (cards != null) ? cards.size() : 0;
    }

    /**
     * Adds a card to the deck and updates the count.
     * @param card the card to add
     */
    public void addCard(FlashcardCard card) {
        if (this.cards == null) {
            this.cards = new ArrayList<>();
        }
        this.cards.add(card);
        updateCardCount();
    }

    /**
     * Removes a card from the deck and updates the count.
     * @param index the index of the card to remove
     * @return the removed card
     * @throws IndexOutOfBoundsException if index is out of range
     */
    public FlashcardCard removeCard(int index) {
        if (this.cards == null || index < 0 || index >= this.cards.size()) {
            throw new IndexOutOfBoundsException("Card index out of range: " + index);
        }
        FlashcardCard removed = this.cards.remove(index);
        updateCardCount();
        return removed;
    }

    /**
     * Checks if this deck was created from a lesson.
     * @return true if sourceType is LESSON
     */
    public boolean isFromLesson() {
        return sourceType == SourceType.LESSON;
    }

    /**
     * Checks if this deck was AI-generated.
     * @return true if sourceType is AI_GENERATED
     */
    public boolean isAiGenerated() {
        return sourceType == SourceType.AI_GENERATED;
    }

    /**
     * Checks if this deck was manually created by the user.
     * @return true if sourceType is USER_CREATED
     */
    public boolean isUserCreated() {
        return sourceType == SourceType.USER_CREATED;
    }

    /**
     * Validates the source consistency:
     * - LESSON type must have sourceId
     * - AI_GENERATED and USER_CREATED should not have sourceId
     * @throws IllegalStateException if source configuration is invalid
     */
    public void validateSourceConsistency() {
        if (sourceType == SourceType.LESSON && sourceId == null) {
            throw new IllegalStateException("LESSON source type requires sourceId");
        }
        if (sourceType != SourceType.LESSON && sourceId != null) {
            throw new IllegalStateException("Non-LESSON source type should not have sourceId");
        }
    }

    // ========== Builder Customization ==========

    /**
     * Custom builder to handle enum conversion for database compatibility.
     */
    public static class FlashcardDeckBuilder {
        /**
         * Sets source type using string value (for database compatibility).
         * @param sourceTypeValue the string value from database
         * @return the builder
         */
        public FlashcardDeckBuilder sourceTypeValue(String sourceTypeValue) {
            this.sourceType = sourceTypeValue != null 
                ? SourceType.fromValue(sourceTypeValue) 
                : null;
            return this;
        }
    }
}
