package com.lexia.backend.dto.ai;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import lombok.Builder;
import lombok.Data;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * DTO for tracking AI usage requests.
 * Contains all information needed to log an AI API call.
 * 
 * <p>
 * Supports comprehensive tracking including:
 * </p>
 * <ul>
 * <li>Token usage (input/output)</li>
 * <li>Response time metrics</li>
 * <li>Success/failure status</li>
 * <li>Flexible metadata (CEFR level, domain, scenario IDs)</li>
 * <li>Prompt template versioning</li>
 * </ul>
 * 
 * @see com.lexia.backend.service.ai.AiUsageTracker
 */
@Data
@Builder
public class AiUsageTrackingRequest {

    /**
     * User who made the AI request.
     */
    @NotNull(message = "User ID is required")
    private UUID userId;

    /**
     * Type of AI content: roleplay, grammar, flashcard, content_generation, etc.
     */
    @NotBlank(message = "Content type is required")
    private String contentType;

    /**
     * AI model used (e.g., gemini-2.0-flash-exp, gemini-1.5-pro).
     */
    @NotBlank(message = "Model ID is required")
    private String modelId;

    /**
     * Number of input tokens sent to the AI.
     */
    @PositiveOrZero(message = "Input tokens must be non-negative")
    @Builder.Default
    private int inputTokens = 0;

    /**
     * Number of output tokens generated by the AI.
     */
    @PositiveOrZero(message = "Output tokens must be non-negative")
    @Builder.Default
    private int outputTokens = 0;

    /**
     * Response time in milliseconds.
     */
    @PositiveOrZero(message = "Response time must be non-negative")
    @Builder.Default
    private int responseTimeMs = 0;

    /**
     * Whether the AI request completed successfully.
     */
    @Builder.Default
    private boolean success = true;

    /**
     * Error message if the request failed.
     */
    private String errorMessage;

    /**
     * Version of the prompt template used.
     * Format: "template_key_v{version}" (e.g., "roleplay_scenario_v1")
     */
    private String promptVersion;

    /**
     * Additional metadata for the request.
     * Common keys: cefrLevel, domain, scenarioId, conversationId, grammarTopic
     */
    @Builder.Default
    private Map<String, Object> metadata = new HashMap<>();

    /**
     * Override cost in USD for fixed-price content (e.g., image generation).
     * When set to a non-null positive value, this bypasses token-based cost
     * calculation.
     * Imagen 4 Fast: $0.02/image, Imagen 4 Ultra: $0.06/image
     */
    private Double overrideCostUsd;

    /**
     * Creates a tracking request for a successful AI call.
     */
    public static AiUsageTrackingRequest success(
            UUID userId,
            String contentType,
            String modelId,
            int inputTokens,
            int outputTokens,
            int responseTimeMs) {
        return AiUsageTrackingRequest.builder()
                .userId(userId)
                .contentType(contentType)
                .modelId(modelId)
                .inputTokens(inputTokens)
                .outputTokens(outputTokens)
                .responseTimeMs(responseTimeMs)
                .success(true)
                .build();
    }

    /**
     * Creates a tracking request for a failed AI call.
     */
    public static AiUsageTrackingRequest failure(
            UUID userId,
            String contentType,
            String modelId,
            int responseTimeMs,
            String errorMessage) {
        return AiUsageTrackingRequest.builder()
                .userId(userId)
                .contentType(contentType)
                .modelId(modelId)
                .inputTokens(0)
                .outputTokens(0)
                .responseTimeMs(responseTimeMs)
                .success(false)
                .errorMessage(errorMessage)
                .build();
    }

    /**
     * Adds a metadata entry.
     * 
     * @return this instance for chaining
     */
    public AiUsageTrackingRequest withMetadata(String key, Object value) {
        if (this.metadata == null) {
            this.metadata = new HashMap<>();
        }
        this.metadata.put(key, value);
        return this;
    }

    /**
     * Sets the CEFR level in metadata.
     * 
     * @return this instance for chaining
     */
    public AiUsageTrackingRequest withCefrLevel(String cefrLevel) {
        return withMetadata("cefrLevel", cefrLevel);
    }

    /**
     * Sets the domain in metadata.
     * 
     * @return this instance for chaining
     */
    public AiUsageTrackingRequest withDomain(String domain) {
        return withMetadata("domain", domain);
    }

    /**
     * Sets the scenario ID in metadata.
     * 
     * @return this instance for chaining
     */
    public AiUsageTrackingRequest withScenarioId(UUID scenarioId) {
        return withMetadata("scenarioId", scenarioId.toString());
    }

    /**
     * Sets the conversation ID in metadata.
     * 
     * @return this instance for chaining
     */
    public AiUsageTrackingRequest withConversationId(UUID conversationId) {
        return withMetadata("conversationId", conversationId.toString());
    }

    /**
     * Calculates total tokens.
     */
    public int getTotalTokens() {
        return inputTokens + outputTokens;
    }
}
