package com.lexia.backend.enums;

/**
 * Status of AI-generated image for flashcard.
 * Used in FlashcardBack to track image generation progress.
 *
 * @author LEXIA Team
 * @since Sprint 6
 */
public enum ImageStatus {
    /**
     * Image generation is queued but not started.
     */
    PENDING,

    /**
     * Image is currently being generated by AI.
     */
    GENERATING,

    /**
     * Image was successfully generated and saved.
     */
    COMPLETED,

    /**
     * Image generation failed (API error, content policy, etc.).
     */
    FAILED
}
